name: json_fetcher
description: Conveniently fetch JSON data from the internet and cache it locally.
version: 2.0.2
repository: https://github.com/justprodev/json_fetcher

topics:
  - http
  - json
  - cache

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.2.1
  hive: 2.2.3
  meta:

  logging:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  http_parser:

  mock_web_server:
    git:
      url: https://github.com/justprodev/MockWebServer.git
      ref: 5.0.0-nullsafety.1