name: json_fetcher
description: Wrapper over standard HttpClient with caching/auth-handling/etc
version: 2.0.0-rc.12
homepage: https://github.com/justprodev/json_fetcher

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.2.1
  hive: 2.2.3
  meta:

  logging:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  http_parser:

  mock_web_server:
    git:
      url: https://github.com/justprodev/MockWebServer.git
      ref: 5.0.0-nullsafety.1