name: json_fetcher
description: Convenient fetching of JSON data with caching, auth, logging. Wrapper over standard Dart http package.
version: 2.0.4
repository: https://github.com/justprodev/json_fetcher

topics:
  - http
  - json
  - cache

environment:
  sdk: ^3.4.0

dependencies:
  http: ^1.3.0
  meta:
  web: ^1.1.0

  logging:

dev_dependencies:
  lints: ">=3.0.0 <6.0.0"
  test: ^1.24.9
  http_parser:

  mock_web_server:
    git:
      url: https://github.com/justprodev/MockWebServer.git
      ref: 5.0.0-nullsafety.1