name: dart_json_fetcher_example
description: Example of using json_fetcher package
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.4.0

dependencies:
  freezed_annotation: ^2.4.4

  json_annotation: ^4.9.0
  json_fetcher: ^2.0.5
  http:

dev_dependencies:
  lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0