name: flutter_json_fetcher_example
description: "Json Fetcher Demo"
publish_to: 'none'

version: 1.0.2

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  super_sliver_list: ^0.4.1

  path_provider: ^2.1.4

  json_fetcher: ^2.0.4
  logging:

  cached_image:
    git:
      url: https://github.com/justprodev/flutter_cached_image.git

  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

dependency_overrides:
  meta: ^1.14.0
