name: dart_web
description: An absolute bare-bones web app.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  web:

  dart_cache_benchmark:
    path: ../dart_cache_benchmark

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^4.0.0
